apiVersion: v1
kind: List
items:
{{- range .Values.objets }}
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .service.name }}
    labels:
      {{- include "chart.labels" $ | nindent 6 }}
  spec:
    type: {{ .service.type }}
    ports:
      - port: {{ .service.port }}
        targetPort: {{ .service.targetPort }}
        protocol: TCP
        name: http
    selector:
        {{- include "chart.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .pod.name }}
{{- end }}
